from __future__ import annotations

from typing import Protocol

from app.domain.models import City, GuestSession, Journey, JourneyAnswer, Route


class CatalogRepository(Protocol):
    def list_cities(self) -> list[City]: ...

    def get_city_by_slug(self, slug: str) -> City | None: ...

    def list_routes_for_city(self, city_id: str) -> list[Route]: ...

    def get_route_by_slug(self, slug: str) -> Route | None: ...

    def get_route_by_id(self, route_id: str) -> Route | None: ...


class GuestSessionRepository(Protocol):
    def add(self, guest_session: GuestSession) -> None: ...

    def get(self, session_id: str) -> GuestSession | None: ...


class JourneyRepository(Protocol):
    def add(self, journey: Journey) -> None: ...

    def get_for_guest(self, journey_id: str, guest_session_id: str) -> Journey | None: ...

    def find_active(self, route_id: str, guest_session_id: str) -> Journey | None: ...

    def add_answer(self, journey_id: str, answer: JourneyAnswer) -> None: ...

    def save(self, journey: Journey) -> None: ...


class UnitOfWork(Protocol):
    catalog: CatalogRepository
    guest_sessions: GuestSessionRepository
    journeys: JourneyRepository

    def __enter__(self) -> UnitOfWork: ...

    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

    def commit(self) -> None: ...
